site_name: Ngine Cloud Docs
repo_url: https://github.com/ngine-io/docs
edit_uri: edit/main/docs/
nav:
  - About: index.md
  - Services:
      - Cloud Targets Service Discovery: sd/index.md

  - Configurations:
      - Service Discoveries:
          - cloudscale.ch: sd/cloudscale_ch.md
          - Exoscale: sd/exoscale.md
theme:
  name: material
  palette:
    primary: cyan
    scheme: slate
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
plugins:
  - search
